name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/generate-snake-game-from-github-contribution-graph@v0.6.0
        with:
          github_user_name: IsaacNjoroge2024
          svg_out_path: dist/github-snake.svg
          gif_out_path: dist/github-snake.gif
          dark_mode: true

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: output
          message: 'Generate Snake Animation'
          add: 'dist'