name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Clean workspace and set up git
      - name: Setup
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clean -fd
          git checkout -B output

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: IsaacNjoroge2024
          svg_out_path: github-contribution-grid-snake.svg

      - name: Push to GitHub
        run: |
          git add github-contribution-grid-snake.svg
          git commit -m "Generate Snake Animation" || exit 0
          git push -f origin output